global k m S Sdot siggen stp noise simout...
    stp_time init_value final_value...
    amplitude frequency noise_power sample_time_noise seed...
    s_initial sdot_initial c_2dot Phi_i_star N M dispturb Phi

    